services:
  flights-maker:
    build:
      context: ./flights-maker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
  server:
    hostname: localhost
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
